luffydiary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace='users')),
    path('',include('luffydiary_logs.urls',namespace='luffydiary_logs')),
]

luffydiary_logs/urls.py
from django.conf.urls import url
from . import views

app_name='[luffydiary_logs]'
urlpatterns =[
    # 主页面
    url(r'^$',views.index, name='index'),
    # 显示所有的主题
    url(r'^topics/$',views.topics, name='topics'),
    # 特定主题的详情页
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    # 添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 添加新条目的的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry, name='new_entry'),
    # 编辑现有条目
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

LoginView.template_name='users/login.html'
app_name='[users]'

urlpatterns=[
    # 登陆页面
    url(r'^login/$',LoginView.as_view(),name='login'),
    # 注销登陆
    url(r'^logout/$',views.logout_view, name='logout'),
    # 注册页面
    url(r'^register/$',views.register,name='register'),

]

luffydiary_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """Entry"""
    #on_delete CASCADE 默认级连删除
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """return models string"""
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

luffydiary_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = {'text'}
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

luffydiary_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    """主页"""
    return render(request,'luffydiary_logs/index.html')

@login_required
def topics(request):
    """"显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'luffydiary_logs/topics.html',context)

@login_required
def topic(request, topic_id):
    """显示单个主题的所有条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于该用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request, 'luffydiary_logs/topic.html',context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        #  未提交数据创建一个新表单
        form = TopicForm()
    else:
        # post请求的数据对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner= request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('luffydiary_logs:topics'))

    context = {'form':form}
    return render(request, 'luffydiary_logs/new_topic.html',context)

@login_required
def new_entry(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 初次请求使用当前条目填充表单
        form = EntryForm()
    else:
        # 对post提交的数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('luffydiary_logs:topic',args=[topic.id]))

    context = {'topic':topic,'form':form}
    return render(request, 'luffydiary_logs/new_entry.html',context)

@login_required
def edit_entry(request, entry_id):
    """编辑现有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # post提交的数据对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('luffydiary_logs:topic',args=[topic.id]))

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request, 'luffydiary_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout,authenticate,login
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('luffydiary_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填好的数据
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 非用户自动登陆，重定向到主页
            authenticated_user = authenticate(username=new_user,password=request.POST['password1'])
        login(request,authenticated_user)
        return HttpResponseRedirect(reverse('luffydiary_logs:index'))
    context ={'form':form}
    return render(request,'users/register.html',context)

luffydiary_logs/templates/luffydiary_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Luffy Diary</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <!--start navbar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-hearder">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                     <a class="navbar-brand" href="{% url 'luffydiary_logs:index' %}">LuffyDiary</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'luffydiary_logs:topics' %}">Topics</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello,{{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">log in</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
            <div class="container">
                <div class="page-header">
                    {% block header %}{% endblock header %}
                </div>
                <div>
                    {% block content %}{% endblock content %}
                </div>
            </div><!-- /container -->
    </body>
</html>

luffydiary_logs/templates/luffydiary_logs/edit_entry.html
{% extends "luffydiary_logs/base.html" %}
{% block content %}
    <p>
        <a href="{% url 'luffydiary_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>Edit entry:</p>
    <form action="{% url 'luffydiary_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
{% endblock content %}

luffydiary_logs/templates/luffydiary_logs/index.html
{% extends "luffydiary_logs/base.html" %}
{% block header %}
    <div class="jumbotorn">
        <h1>Track you learning!</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url "users:register" %}">
            Register an account
        </a>
        to make you own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry
        summarizing waht you've learned.
    </h2>
{% endblock content %}

luffydiary_logs/templates/luffydiary_logs/new_entry.html
{% extends "luffydiary_logs/base.html" %}
{% block content %}
    <p>
        <a href="{% url 'luffydiary_logs:topic' topic.id %}">
            {{ topic }}
        </a>
    </p>
    <p>
        Add a new entry:
    </p>
    <form action="{% url 'luffydiary_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p  }}
        <button name="submit">add entry</button>
    </form>
{% endblock content %}

luffydiary_logs/templates/luffydiary_logs/new_topic.html
{% extends "luffydiary_logs/base.html" %}
{% block content %}
    <p>Add a new topic</p>
    <form action="{% url 'luffydiary_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>
{% endblock content %}

luffydiary_logs/templates/luffydiary_logs/topic.html
{% extends "luffydiary_logs/base.html" %}

{% block header %}
    <h1>{{ topic }}</h1>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'luffydiary_logs:new_entry' topic.id %}">add a new entry</a>
    </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'luffydiary_logs:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div><!--panel-->
    {% empty %}
        There are no entries for this topic yet!
    {% endfor %}
{% endblock content %}

luffydiary_logs/templates/luffydiary_logs/topics.html
{% extends "luffydiary_logs/base.html" %}
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'luffydiary_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet!</li>
    {% endfor %}
</ul>
    <a href="{% url 'luffydiary_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}

users/templates/users/login.html
{% extends "luffydiary_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'luffydiary_logs:index' %}">
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "luffydiary_logs/base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'luffydiary_logs:index' %}">
    </form>
{% endblock content %}